MVCPaging/MVCPaging/Models/DatabaseHelper.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVCGridPaging.Models
{
    public class DatabaseHelper
    {
        public int FillData()
        {
            using (MyDatabaseEntities db = new MyDatabaseEntities())
            {
                var maxRecords = 10000;
                for (var counter = 0; counter < maxRecords; counter++)
                    db.Customers.Add(new Customer()
                    {
                        CustomerName = string.Format("Name_{0}", counter),
                        Address = string.Format("Address_{0}", counter),
                        EmailAddress = string.Format("Email_{0}", counter),
                        PostCode = string.Format("PO_{0}", counter),
                        City = string.Format("City_{0}", counter),

                    });
                return db.SaveChanges();
            }
            return -1;
        }
    }
}

MVCPaging/MVCPaging/Controllers/HomeController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace MVCGridPaging.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index(int page = 1)
        {            
            int pageSize = 10;
            int noPages = 0;
            int noRecords = 0;

            List<Customer> customerList = new List<Customer>();
            using (MyDatabaseEntities db = new MyDatabaseEntities())
            {
                noRecords = db.Customers.Count();
                noPages = (noRecords / pageSize) + ((noRecords % pageSize) > 0 ? 1:0);
                int offset = (page - 1) * pageSize;
                customerList = db.Customers.OrderBy(cust => cust.CustomerID).Skip(offset).Take(pageSize).ToList();
            }

            ViewBag.TotalRows = noRecords;
            ViewBag.PageSize = pageSize;

            return View(customerList);
        }

        
    }
}

MVCPaging/MVCPaging/Controllers/Version2Controller.cs
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web.Mvc;

namespace MVCGridPaging.Controllers
{
    public class Version2Controller : Controller
    {
        public ActionResult Index(int page = 1)
        {
            int pageSize = 10;
            int noPages = 0;
            int noRecords = 0;
            
            var customerList = new List<Customer>();
            
            using (SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["CustomerDatabase"].ConnectionString))
            {
                SqlCommand cmd = new SqlCommand("GetCustomers", con);
                cmd.CommandType = System.Data.CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@PageNo", page);
                cmd.Parameters.AddWithValue("@NoOfRecord", pageSize);

                SqlParameter TotalRecordSP = new SqlParameter("@TotalRecord", System.Data.SqlDbType.Int);
                TotalRecordSP.Direction = System.Data.ParameterDirection.Output;
                cmd.Parameters.Add(TotalRecordSP);

                var dt = new DataTable();
                if (con.State != ConnectionState.Open)
                {
                    con.Open();
                }
                dt.Load(cmd.ExecuteReader());
                
                if (TotalRecordSP.Value != null)
                {
                    int.TryParse(TotalRecordSP.Value.ToString(), out noRecords);
                }
                var dataTable = dt.AsEnumerable();
                customerList = (from DataRow row in dt.Rows
                                select new Customer()
                                {
                                    CustomerID = (int) row["CustomerID"],
                                    CustomerName = row["CustomerName"] as string,
                                    Address = row["Address"] as string,
                                    EmailAddress = row["EmailAddress"] as string,
                                    PostCode = row["PostCode"] as string,
                                    City = row["City"] as string,
                                }
                                    ).ToList();
            }

            noPages = (noRecords / pageSize) + ((noRecords % pageSize) > 0 ? 1 : 0);
            
            ViewBag.TotalRows = noRecords;
            ViewBag.PageSize = pageSize;
            return View(customerList);
        }        
    }
}

MVCPaging/MVCPaging/Views/Home/Index.cshtml
@model List<Customer>

@{
    ViewBag.Title = "MVC Grid Paging with EntityFramework";
    // create instance of the grid
    var grid = new WebGrid(rowsPerPage: ViewBag.PageSize, canPage: true);
    grid.Bind(source: Model, autoSortAndPage: false, rowCount: ViewBag.TotalRows);
}

<style type="text/css">
    table.gridtable {
        font-family: verdana,arial,sans-serif;
        font-size: 11px;
        color: #333333;
        border-width: 1px;
        border-color: #666666;
        border-collapse: collapse;
    }

        table.gridtable th {
            border-width: 1px;
            padding: 8px;
            border-style: solid;
            border-color: #666666;
            background-color: #dedede;
        }

        table.gridtable td {
            border-width: 1px;
            padding: 8px;
            border-style: solid;
            border-color: #666666;
            background-color: #ffffff;
        }
</style>

<h2>MVC Grid Paging with EntityFramework</h2>
<div>
    @grid.GetHtml(tableStyle: "gridtable",
        mode: WebGridPagerModes.All,        
        firstText:"First", lastText:"Last",
        nextText:"Next", previousText:"Previous",
        columns: grid.Columns(
                    grid.Column("CustomerID", "Customer ID"),
                    grid.Column("CustomerName", "Customer Name"),
                    grid.Column("Address", "Address"),
                    grid.Column("EmailAddress", "Email Address"),
                    grid.Column("City", "City"),
                    grid.Column("PostCode", "PostCode")
        )
    )
</div>

MVCPaging/MVCPaging/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MVC Grid pagination", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Entity Framework", "Index", "Home")</li>
                    <li>@Html.ActionLink("Stored procedure", "Index", "Version2")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MVCPaging/MVCPaging/Views/Version2/Index.cshtml
@model List<Customer>

@{
    ViewBag.Title = "MVC Grid Paging with Stored Procedure";
    // create instance of the grid
    var grid = new WebGrid(rowsPerPage: ViewBag.PageSize, canPage: true);
    grid.Bind(source: Model, autoSortAndPage: false, rowCount: ViewBag.TotalRows);
}

<style type="text/css">
    table.gridtable {
        font-family: verdana,arial,sans-serif;
        font-size: 11px;
        color: #333333;
        border-width: 1px;
        border-color: #666666;
        border-collapse: collapse;
    }

        table.gridtable th {
            border-width: 1px;
            padding: 8px;
            border-style: solid;
            border-color: #666666;
            background-color: #dedede;
        }

        table.gridtable td {
            border-width: 1px;
            padding: 8px;
            border-style: solid;
            border-color: #666666;
            background-color: #ffffff;
        }
</style>

<h2>MVC Grid Paging with Stored Procedure</h2>
<div>
    @grid.GetHtml(tableStyle: "gridtable",
        mode: WebGridPagerModes.All,
        firstText: "First", lastText: "Last",
        nextText: "Next", previousText: "Previous",
        columns: grid.Columns(
                    grid.Column("CustomerID", "Customer ID"),
                    grid.Column("CustomerName", "Customer Name"),
                    grid.Column("Address", "Address"),
                    grid.Column("EmailAddress", "Email Address"),
                    grid.Column("City", "City"),
                    grid.Column("PostCode", "PostCode")
        )
    )
</div>